name: "🐛 Bug Report"
description: "Report something that is not working as expected"
title: "🐛 Bug Report: "
labels: ["bug"]
assignees:
  - timokoessler
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: A brief description of the bug.
      placeholder: What is the bug about? What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the bug.
      placeholder: How can the bug be reproduced?
    validations:
      required: true
  - type: textarea
    id: error-message
    attributes:
      label: Provide the error message and stack trace
      placeholder: Paste the error message and stack trace here, if available
    validations:
      required: false
  - type: input
    id: win-version
    attributes:
      label: What version of Windows are you using?
      description: Please enter the entire version number, e.g. Windows 11 26100
      placeholder: Your Windows version
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: What version of the app are you using?
      placeholder: The app version, e.g. 1.0.0
    validations:
      required: true
  - type: dropdown
    id: app-edition
    attributes:
      label: What edition of the app are you using?
      options:
        - Microsoft Store App
        - Installer
        - Portable App
    validations:
      required: true
  - type: checkboxes
    id:
    attributes:
      label: Are you willing to help with the implementation?
      description: If you are willing to help with the implementation, please check the box below.
      options:
        - label: Yes
      validations:
        required: false
