name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["feature"]
assignees:
  - timokoessler
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for this project!
  - type: textarea
    id: idea
    attributes:
      label: What is your idea?
      description: Describe the feature or enhancement you are proposing.
      placeholder: What feature would you like to see added to this project?
    validations:
      required: true

